// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	ChainID              string   `protobuf:"bytes,1,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	Parent               string   `protobuf:"bytes,2,opt,name=Parent,proto3" json:"Parent,omitempty"`
	Index                uint64   `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	Timestamp            uint32   `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Packager             string   `protobuf:"bytes,5,opt,name=Packager,proto3" json:"Packager,omitempty"`
	Txc                  uint32   `protobuf:"varint,6,opt,name=Txc,proto3" json:"Txc,omitempty"`
	Txs                  []byte   `protobuf:"bytes,7,opt,name=Txs,proto3" json:"Txs,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,8,opt,name=ExtraData,proto3" json:"ExtraData,omitempty"`
	AppendData           []byte   `protobuf:"bytes,9,opt,name=AppendData,proto3" json:"AppendData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *Block) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Block) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Block) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetPackager() string {
	if m != nil {
		return m.Packager
	}
	return ""
}

func (m *Block) GetTxc() uint32 {
	if m != nil {
		return m.Txc
	}
	return 0
}

func (m *Block) GetTxs() []byte {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *Block) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *Block) GetAppendData() []byte {
	if m != nil {
		return m.AppendData
	}
	return nil
}

type GenBlock struct {
	ChainID              string            `protobuf:"bytes,1,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	Parent               string            `protobuf:"bytes,2,opt,name=Parent,proto3" json:"Parent,omitempty"`
	Index                uint64            `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`
	Timestamp            uint32            `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Packager             string            `protobuf:"bytes,5,opt,name=Packager,proto3" json:"Packager,omitempty"`
	Txc                  uint32            `protobuf:"varint,6,opt,name=Txc,proto3" json:"Txc,omitempty"`
	Txs                  []byte            `protobuf:"bytes,7,opt,name=Txs,proto3" json:"Txs,omitempty"`
	ExtraData            []byte            `protobuf:"bytes,8,opt,name=ExtraData,proto3" json:"ExtraData,omitempty"`
	AppendData           []byte            `protobuf:"bytes,9,opt,name=AppendData,proto3" json:"AppendData,omitempty"`
	Award                map[string]uint64 `protobuf:"bytes,10,rep,name=Award,proto3" json:"Award,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	SuperNodes           []*Node           `protobuf:"bytes,11,rep,name=SuperNodes,proto3" json:"SuperNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenBlock) Reset()         { *m = GenBlock{} }
func (m *GenBlock) String() string { return proto.CompactTextString(m) }
func (*GenBlock) ProtoMessage()    {}
func (*GenBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}

func (m *GenBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenBlock.Unmarshal(m, b)
}
func (m *GenBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenBlock.Marshal(b, m, deterministic)
}
func (m *GenBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenBlock.Merge(m, src)
}
func (m *GenBlock) XXX_Size() int {
	return xxx_messageInfo_GenBlock.Size(m)
}
func (m *GenBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_GenBlock.DiscardUnknown(m)
}

var xxx_messageInfo_GenBlock proto.InternalMessageInfo

func (m *GenBlock) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *GenBlock) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *GenBlock) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GenBlock) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GenBlock) GetPackager() string {
	if m != nil {
		return m.Packager
	}
	return ""
}

func (m *GenBlock) GetTxc() uint32 {
	if m != nil {
		return m.Txc
	}
	return 0
}

func (m *GenBlock) GetTxs() []byte {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *GenBlock) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *GenBlock) GetAppendData() []byte {
	if m != nil {
		return m.AppendData
	}
	return nil
}

func (m *GenBlock) GetAward() map[string]uint64 {
	if m != nil {
		return m.Award
	}
	return nil
}

func (m *GenBlock) GetSuperNodes() []*Node {
	if m != nil {
		return m.SuperNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*Block)(nil), "im.Block")
	proto.RegisterType((*GenBlock)(nil), "im.GenBlock")
	proto.RegisterMapType((map[string]uint64)(nil), "im.GenBlock.AwardEntry")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xc9, 0xfa, 0x67, 0xed, 0x5b, 0x05, 0x09, 0xa2, 0xa1, 0x88, 0x94, 0x9d, 0x72, 0xb1,
	0x07, 0xbd, 0x0c, 0x6f, 0xd3, 0x0d, 0xd9, 0x45, 0x46, 0xdc, 0x17, 0xc8, 0xda, 0xa0, 0xa5, 0x6b,
	0x5a, 0xd2, 0x4c, 0xbb, 0xa3, 0x9f, 0xd7, 0x2f, 0x21, 0x49, 0x37, 0xbb, 0xef, 0xe0, 0xed, 0x7d,
	0x7e, 0x4f, 0x9e, 0x97, 0xe4, 0x21, 0x10, 0x6d, 0xb6, 0x75, 0x56, 0xa6, 0x8d, 0xaa, 0x75, 0x8d,
	0x47, 0x45, 0x15, 0x83, 0xac, 0x73, 0xd1, 0xeb, 0xc9, 0x0f, 0x02, 0xef, 0xc9, 0xf8, 0x98, 0xc0,
	0xf8, 0xf9, 0x83, 0x17, 0x72, 0x39, 0x27, 0x28, 0x41, 0x34, 0x64, 0x47, 0x89, 0xaf, 0xc0, 0x5f,
	0x71, 0x25, 0xa4, 0x26, 0x23, 0x6b, 0x1c, 0x14, 0xbe, 0x04, 0x6f, 0x29, 0x73, 0xd1, 0x11, 0x27,
	0x41, 0xd4, 0x65, 0xbd, 0xc0, 0x37, 0x10, 0xae, 0x8b, 0x4a, 0xb4, 0x9a, 0x57, 0x0d, 0x71, 0x13,
	0x44, 0xcf, 0xd9, 0x00, 0x70, 0x0c, 0xc1, 0x8a, 0x67, 0x25, 0x7f, 0x17, 0x8a, 0x78, 0x76, 0xdb,
	0x9f, 0xc6, 0x17, 0xe0, 0xac, 0xbb, 0x8c, 0xf8, 0x36, 0x63, 0xc6, 0x9e, 0xb4, 0x64, 0x9c, 0x20,
	0x7a, 0x66, 0x48, 0x6b, 0xb6, 0x2f, 0x3a, 0xad, 0xf8, 0x9c, 0x6b, 0x4e, 0x02, 0xcb, 0x07, 0x80,
	0x6f, 0x01, 0x66, 0x4d, 0x23, 0x64, 0x6e, 0xed, 0xd0, 0xda, 0x27, 0x64, 0xf2, 0xed, 0x40, 0xf0,
	0x22, 0xe4, 0xbf, 0x79, 0x30, 0xbe, 0x03, 0x6f, 0xf6, 0xc5, 0x55, 0x4e, 0x20, 0x71, 0x68, 0x74,
	0x7f, 0x9d, 0x16, 0x55, 0x7a, 0x2c, 0x20, 0xb5, 0xce, 0x42, 0x6a, 0xb5, 0x67, 0xfd, 0x29, 0x4c,
	0x01, 0xde, 0x76, 0x8d, 0x50, 0xaf, 0x75, 0x2e, 0x5a, 0x12, 0xd9, 0x4c, 0x60, 0x32, 0x06, 0xb0,
	0x13, 0x2f, 0x9e, 0x02, 0x0c, 0x71, 0x73, 0xed, 0x52, 0xec, 0x0f, 0x35, 0x9a, 0xd1, 0x54, 0xf5,
	0xc9, 0xb7, 0x3b, 0x61, 0x1b, 0x74, 0x59, 0x2f, 0x1e, 0x47, 0x53, 0xb4, 0xf1, 0xed, 0xc7, 0x7b,
	0xf8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x82, 0x4c, 0x45, 0x75, 0x97, 0x02, 0x00, 0x00,
}
