// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaininfo.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChainInfo struct {
	ChainID              string   `protobuf:"bytes,1,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	BlockIndex           uint64   `protobuf:"varint,2,opt,name=BlockIndex,proto3" json:"BlockIndex,omitempty"`
	Indexes              []byte   `protobuf:"bytes,3,opt,name=Indexes,proto3" json:"Indexes,omitempty"`
	FinalCVFS            []byte   `protobuf:"bytes,4,opt,name=FinalCVFS,proto3" json:"FinalCVFS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainInfo) Reset()         { *m = ChainInfo{} }
func (m *ChainInfo) String() string { return proto.CompactTextString(m) }
func (*ChainInfo) ProtoMessage()    {}
func (*ChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06c819fdb62c369, []int{0}
}

func (m *ChainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainInfo.Unmarshal(m, b)
}
func (m *ChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainInfo.Marshal(b, m, deterministic)
}
func (m *ChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainInfo.Merge(m, src)
}
func (m *ChainInfo) XXX_Size() int {
	return xxx_messageInfo_ChainInfo.Size(m)
}
func (m *ChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChainInfo proto.InternalMessageInfo

func (m *ChainInfo) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *ChainInfo) GetBlockIndex() uint64 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *ChainInfo) GetIndexes() []byte {
	if m != nil {
		return m.Indexes
	}
	return nil
}

func (m *ChainInfo) GetFinalCVFS() []byte {
	if m != nil {
		return m.FinalCVFS
	}
	return nil
}

func init() {
	proto.RegisterType((*ChainInfo)(nil), "im.ChainInfo")
}

func init() { proto.RegisterFile("chaininfo.proto", fileDescriptor_c06c819fdb62c369) }

var fileDescriptor_c06c819fdb62c369 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0x48, 0xcc,
	0xcc, 0xcb, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0xcc, 0x55,
	0xaa, 0xe5, 0xe2, 0x74, 0x06, 0x09, 0x7b, 0xe6, 0xa5, 0xe5, 0x0b, 0x49, 0x70, 0xb1, 0x43, 0x38,
	0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x1c, 0x17, 0x97, 0x53, 0x4e,
	0x7e, 0x72, 0xb6, 0x67, 0x5e, 0x4a, 0x6a, 0x85, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x92,
	0x08, 0x48, 0x27, 0x98, 0x91, 0x5a, 0x2c, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0xe3, 0x0a,
	0xc9, 0x70, 0x71, 0xba, 0x65, 0xe6, 0x25, 0xe6, 0x38, 0x87, 0xb9, 0x05, 0x4b, 0xb0, 0x80, 0xe5,
	0x10, 0x02, 0x49, 0x6c, 0x60, 0x97, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xd5, 0xe0,
	0x5d, 0x9c, 0x00, 0x00, 0x00,
}
