// Code generated by protoc-gen-go. DO NOT EDIT.
// source: electoral.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Electoral struct {
	BestIndex            uint64   `protobuf:"varint,1,opt,name=BestIndex,proto3" json:"BestIndex,omitempty"`
	BlockIndex           uint64   `protobuf:"varint,2,opt,name=BlockIndex,proto3" json:"BlockIndex,omitempty"`
	From                 []byte   `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	ToPeerId             string   `protobuf:"bytes,4,opt,name=ToPeerId,proto3" json:"ToPeerId,omitempty"`
	Time                 uint32   `protobuf:"varint,5,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Electoral) Reset()         { *m = Electoral{} }
func (m *Electoral) String() string { return proto.CompactTextString(m) }
func (*Electoral) ProtoMessage()    {}
func (*Electoral) Descriptor() ([]byte, []int) {
	return fileDescriptor_df52258aa8dbb3ee, []int{0}
}

func (m *Electoral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Electoral.Unmarshal(m, b)
}
func (m *Electoral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Electoral.Marshal(b, m, deterministic)
}
func (m *Electoral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Electoral.Merge(m, src)
}
func (m *Electoral) XXX_Size() int {
	return xxx_messageInfo_Electoral.Size(m)
}
func (m *Electoral) XXX_DiscardUnknown() {
	xxx_messageInfo_Electoral.DiscardUnknown(m)
}

var xxx_messageInfo_Electoral proto.InternalMessageInfo

func (m *Electoral) GetBestIndex() uint64 {
	if m != nil {
		return m.BestIndex
	}
	return 0
}

func (m *Electoral) GetBlockIndex() uint64 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *Electoral) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Electoral) GetToPeerId() string {
	if m != nil {
		return m.ToPeerId
	}
	return ""
}

func (m *Electoral) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Electoral)(nil), "im.Electoral")
}

func init() { proto.RegisterFile("electoral.proto", fileDescriptor_df52258aa8dbb3ee) }

var fileDescriptor_df52258aa8dbb3ee = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcd, 0x49, 0x4d,
	0x2e, 0xc9, 0x2f, 0x4a, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0xcc, 0x55,
	0xea, 0x65, 0xe4, 0xe2, 0x74, 0x85, 0x89, 0x0b, 0xc9, 0x70, 0x71, 0x3a, 0xa5, 0x16, 0x97, 0x78,
	0xe6, 0xa5, 0xa4, 0x56, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x21, 0x04, 0x84, 0xe4, 0xb8,
	0xb8, 0x9c, 0x72, 0xf2, 0x93, 0xb3, 0x21, 0xd2, 0x4c, 0x60, 0x69, 0x24, 0x11, 0x21, 0x21, 0x2e,
	0x16, 0xb7, 0xa2, 0xfc, 0x5c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0x5b, 0x48, 0x8a,
	0x8b, 0x23, 0x24, 0x3f, 0x20, 0x35, 0xb5, 0xc8, 0x33, 0x45, 0x82, 0x45, 0x81, 0x51, 0x83, 0x33,
	0x08, 0xce, 0x07, 0xa9, 0x0f, 0xc9, 0xcc, 0x4d, 0x95, 0x60, 0x55, 0x60, 0xd4, 0xe0, 0x0d, 0x02,
	0xb3, 0x93, 0xd8, 0xc0, 0x4e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x12, 0x19, 0x30, 0x6d,
	0xad, 0x00, 0x00, 0x00,
}
