// Code generated by protoc-gen-go. DO NOT EDIT.
// source: minined.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Minined struct {
	MBlock               *Block   `protobuf:"bytes,1,opt,name=MBlock,proto3" json:"MBlock,omitempty"`
	Batcher              []byte   `protobuf:"bytes,2,opt,name=Batcher,proto3" json:"Batcher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Minined) Reset()         { *m = Minined{} }
func (m *Minined) String() string { return proto.CompactTextString(m) }
func (*Minined) ProtoMessage()    {}
func (*Minined) Descriptor() ([]byte, []int) {
	return fileDescriptor_c89ff5b8befa16ed, []int{0}
}

func (m *Minined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Minined.Unmarshal(m, b)
}
func (m *Minined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Minined.Marshal(b, m, deterministic)
}
func (m *Minined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Minined.Merge(m, src)
}
func (m *Minined) XXX_Size() int {
	return xxx_messageInfo_Minined.Size(m)
}
func (m *Minined) XXX_DiscardUnknown() {
	xxx_messageInfo_Minined.DiscardUnknown(m)
}

var xxx_messageInfo_Minined proto.InternalMessageInfo

func (m *Minined) GetMBlock() *Block {
	if m != nil {
		return m.MBlock
	}
	return nil
}

func (m *Minined) GetBatcher() []byte {
	if m != nil {
		return m.Batcher
	}
	return nil
}

func init() {
	proto.RegisterType((*Minined)(nil), "im.Minined")
}

func init() { proto.RegisterFile("minined.proto", fileDescriptor_c89ff5b8befa16ed) }

var fileDescriptor_c89ff5b8befa16ed = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xcd, 0xcc, 0xcb,
	0xcc, 0x4b, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0xcc, 0x95, 0xe2, 0x4e,
	0xca, 0xc9, 0x4f, 0xce, 0x86, 0x08, 0x28, 0xb9, 0x71, 0xb1, 0xfb, 0x42, 0x54, 0x08, 0x29, 0x72,
	0xb1, 0xf9, 0x3a, 0x81, 0xa4, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x38, 0xf5, 0x32, 0x73,
	0xf5, 0xc0, 0x02, 0x41, 0x50, 0x09, 0x21, 0x09, 0x2e, 0x76, 0xa7, 0xc4, 0x92, 0xe4, 0x8c, 0xd4,
	0x22, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x37, 0x89, 0x0d, 0x6c, 0x9c, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x4f, 0x63, 0xb9, 0x3f, 0x70, 0x00, 0x00, 0x00,
}
