// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package im

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_Normal     TransactionType = 0
	TransactionType_Unrecorded TransactionType = 1
)

var TransactionType_name = map[int32]string{
	0: "Normal",
	1: "Unrecorded",
}

var TransactionType_value = map[string]int32{
	"Normal":     0,
	"Unrecorded": 1,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

type Transaction struct {
	BlockIndex           uint64          `protobuf:"varint,1,opt,name=BlockIndex,proto3" json:"BlockIndex,omitempty"`
	From                 []byte          `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To                   []byte          `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Value                uint64          `protobuf:"varint,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Type                 TransactionType `protobuf:"varint,5,opt,name=Type,proto3,enum=im.TransactionType" json:"Type,omitempty"`
	Tid                  uint64          `protobuf:"varint,6,opt,name=Tid,proto3" json:"Tid,omitempty"`
	Sig                  []byte          `protobuf:"bytes,7,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Data                 string          `protobuf:"bytes,8,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetBlockIndex() uint64 {
	if m != nil {
		return m.BlockIndex
	}
	return 0
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_Normal
}

func (m *Transaction) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *Transaction) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *Transaction) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("im.TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterType((*Transaction)(nil), "im.Transaction")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x4d, 0xb7, 0x5b, 0x75, 0x94, 0x5a, 0x47, 0x0f, 0x73, 0x92, 0xe2, 0xc5, 0x22, 0xd8,
	0x83, 0xfe, 0x03, 0x11, 0xc1, 0x8b, 0x87, 0x1a, 0xbd, 0xc7, 0x36, 0x48, 0xb0, 0xc9, 0x2c, 0x31,
	0x82, 0xfe, 0x43, 0x7f, 0x96, 0x64, 0x3c, 0x58, 0xf6, 0xf6, 0xe5, 0xbd, 0xbc, 0x79, 0xc3, 0xc0,
	0x71, 0x8a, 0x26, 0x7c, 0x98, 0x31, 0x39, 0x0e, 0xfd, 0x26, 0x72, 0x62, 0x2c, 0x9c, 0x3f, 0xff,
	0x51, 0x70, 0xa0, 0xff, 0x1d, 0x3c, 0x03, 0xb8, 0x9d, 0x79, 0x7c, 0x7f, 0x08, 0x93, 0xfd, 0x22,
	0xd5, 0xaa, 0xae, 0x1c, 0x16, 0x0a, 0x22, 0x94, 0xf7, 0x91, 0x3d, 0x15, 0xad, 0xea, 0x0e, 0x07,
	0x61, 0xac, 0xa1, 0xd0, 0x4c, 0x2b, 0x51, 0x0a, 0xcd, 0x78, 0x0a, 0xeb, 0x17, 0x33, 0x7f, 0x5a,
	0x2a, 0x25, 0xfe, 0xf7, 0xc0, 0x0b, 0x28, 0xf5, 0xf7, 0xc6, 0xd2, 0xba, 0x55, 0x5d, 0x7d, 0x7d,
	0xd2, 0x3b, 0xdf, 0x2f, 0x8a, 0xb3, 0x35, 0xc8, 0x07, 0x6c, 0x60, 0xa5, 0xdd, 0x44, 0x95, 0x84,
	0x33, 0x66, 0xe5, 0xc9, 0xbd, 0xd1, 0xae, 0x34, 0x64, 0xcc, 0x6b, 0xdc, 0x99, 0x64, 0x68, 0xaf,
	0x55, 0xdd, 0xfe, 0x20, 0x7c, 0x79, 0x05, 0x47, 0x5b, 0x03, 0x11, 0xa0, 0x7a, 0xe4, 0xe8, 0xcd,
	0xdc, 0xec, 0x60, 0x0d, 0xf0, 0x1c, 0xa2, 0x1d, 0x39, 0x4e, 0x76, 0x6a, 0xd4, 0x6b, 0x25, 0x47,
	0xb8, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x19, 0xc9, 0xfc, 0xf0, 0x19, 0x01, 0x00, 0x00,
}
